version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: recruit-exam
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: moppy_test
      MYSQL_USER: guest_user
      MYSQL_PASSWORD: guest_password
      TZ: Japan
    ports:
      - 13306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
